from django.db import models

import subprocess

class Openvpn(models.Model):
    name = models.CharField(max_length=255, unique=True)
    description = models.TextField(blank=True, null=True)
    port = models.IntegerField(default=1194)
    tun_ip = models.IPAddressField()
    static_key = models.TextField()

    def __str__(self):
        return self.name

class OpenvpnClient(Openvpn):
    gateway = models.CharField(max_length=255)
    server_ip = models.IPAddressField()

    def save(self, *args, **kwargs):
        configfile = "/tmp/%s.conf" % self.name
        keyfile = "/tmp/%s.key" % self.name
        with open(keyfile, "w") as kf:
            kf.write(self.static_key)
        with open(configfile, "w") as cf:
            cf.write("# autogenerated configuration")
            cf.write("# for %s. Do not edit!")
            cf.write("remote %s" % self.gateway)
            cf.write("port %d" % self.port)
            cf.write("dev tun")
            cf.write("ifconfig %s %s" % (self.tun_ip, self.server_ip))

# saved for later use in server model
#        genkeycmd = "openvpn --genkey --secret %s" % keyfile
#        p = subprocess.Popen(genkeycmd)
#        if p.wait() != 0:
#            raise Exception("could not generate static key")

        deploycmd = "/usr/local/bin/deployconfig.sh %s" % self.name
        p = subprocess.Popen(deploycmd)
        if p.wait() != 0:
            raise Exception("could not deploy config and/or key file(s)")

        super(OpenvpnClient, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        rmcmd = "/usr/local/bin/rmconfig.sh %s" % self.name
        p = subprocess.Popen(rmcmd)
        if p.wait() != 0:
            raise Exception("could not delete config and/or key file(s)")

        super(OpenvpnClient, self).save(*args, **kwargs)








