# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import openvpn.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressPort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.GenericIPAddressField(default='0.0.0.0')),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Openvpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('tun_ip', models.GenericIPAddressField()),
                ('config', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('start_on_boot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OpenvpnClient',
            fields=[
                ('openvpn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openvpn.Openvpn')),
                ('gateway', models.CharField(max_length=255)),
                ('server_port', models.IntegerField(default=1194)),
                ('server_ip', models.GenericIPAddressField()),
                ('static_key', models.TextField()),
            ],
            bases=('openvpn.openvpn',),
        ),
        migrations.CreateModel(
            name='OpenvpnServer',
            fields=[
                ('openvpn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openvpn.Openvpn')),
                ('client_ip', models.GenericIPAddressField()),
                ('static_key', models.TextField(default=openvpn.models.Tools.create_key)),
            ],
            bases=('openvpn.openvpn',),
        ),
        migrations.AddField(
            model_name='openvpn',
            name='bind_to',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='openvpn.AddressPort'),
        ),
        migrations.AlterUniqueTogether(
            name='addressport',
            unique_together=set([('address', 'port')]),
        ),
        migrations.AlterUniqueTogether(
            name='openvpnclient',
            unique_together=set([('gateway', 'server_port')]),
        ),
    ]
