# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-06 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Openvpn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('port', models.IntegerField(default=1194)),
                ('tun_ip', models.GenericIPAddressField()),
                ('static_key', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenvpnClient',
            fields=[
                ('openvpn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openvpn.Openvpn')),
                ('gateway', models.CharField(max_length=255)),
                ('server_ip', models.GenericIPAddressField()),
            ],
            bases=('openvpn.openvpn',),
        ),
    ]
