# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='openvpnclient',
            name='local_port',
            field=models.IntegerField(default=1194),
        ),
    ]
