# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenvpnServer',
            fields=[
                ('openvpn_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='openvpn.Openvpn')),
                ('client_ip', models.GenericIPAddressField()),
            ],
            bases=('openvpn.openvpn',),
        ),
        migrations.AlterField(
            model_name='openvpn',
            name='static_key',
            field=models.TextField(editable=False),
        ),
    ]
