# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-11 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0002_openvpnclient_local_port'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpnclient',
            name='local_port',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='openvpnclient',
            name='port',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='openvpnserver',
            name='port',
            field=models.IntegerField(unique=True),
        ),
    ]
