# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-06 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0002_auto_20161006_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpn',
            name='static_key',
            field=models.TextField(),
        ),
    ]
