# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 11:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0004_auto_20161006_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='openvpn',
            name='configfile',
            field=models.CharField(blank=True, editable=False, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='openvpnserver',
            name='static_key',
            field=models.TextField(default='#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----\n1f0e5fbcdfffd9182216208905661842\nabbbaf53164eb28a05c28b1572d20436\n9b372bc0b37fa76dda67861c848fcd37\n5917e7a4fba562cb6d96b6d03a6f927e\n877498d0b906c70bb48216ab9e0206ff\n6569a69027b2b2223ce9d09b3eeb2b42\n831948b6b57b0bb0835ab016db8e3cce\n8645c193351548cf7853497a2a06ac14\n458ce3fb5f5da38e1fdf188d81ee55c7\nac04581ac9d8a6311c7be421081163f8\n082cace86ab7decffe235572d6e860f9\n44dc6d7cd6ba59aef76c0db19ff26abc\n8fe091a047d2941859ed5849f5d050ad\n95f5b76aadca0c04e2d7c0067c832dfc\nb6ac30fb8328a53a0580c863923add8d\n44a4abd2d6726592fb50dc5cda412875\n-----END OpenVPN Static key V1-----\n'),
        ),
    ]
