# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0005_auto_20161007_1118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='openvpn',
            old_name='configfile',
            new_name='config',
        ),
        migrations.AddField(
            model_name='openvpn',
            name='start_on_boot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='openvpnserver',
            name='static_key',
            field=models.TextField(default='#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----\n9aa26c7b486122f33a814ef5b0584ad2\n42e8f5fabf6d1154a2e440c2f187262c\n5ee16dccb1f278b95dd3caed114a2793\ne5d97f1257b8d30c24fe24f9e727a492\n2862f4802de9a412c8462255224d7fe4\n4f4d02d23cdbc72786eb15b7e8e9f09e\nacf17fd726e475640f1e5adfe07360ec\n839c5cf2d37e1e7f18c54f4da991838e\n2ef49908d26df1c1c8dd4be82833917d\nf97a1436b16e6b4946ece57d1d4d67f4\nd14c3b992aca4a65070a32c34f98e1b3\n7d38370d93ac451852020db1cb46d6c9\neadfd9f8855b562bf152b565db9e93c9\n0fdaf3c932ff9003272ba1de317df8bb\nd72b6027cdf3b11942fbf8a4ef66f240\n4ff4104569273bf729392d33c938b02e\n-----END OpenVPN Static key V1-----\n'),
        ),
    ]
