# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-10-07 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0006_auto_20161007_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpnserver',
            name='static_key',
            field=models.TextField(default='#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----\n5b30fb69f419b65d07e5b5b696785916\n39a9fa9ea86f8b8d31ebd22f9eb74288\n19d09a22e637957fab6d8949ab070d61\n3cc218deed3c3f97a21f4abf2d0c2c18\n21cc165429ec5140cf30e00eaabe4de3\n0b3ccbba334fb23899a29e0a1ceea1db\nf412916a7c96f35fea0142bcc9c514ae\n58580d9a1cf4160f2f1551e85c94d77c\n4c7d2bc5d8cab4af403377d55b410c1c\n2214cf169a5697d876a3182a6d13ee56\n42fc5a67c98a0828f20c2c3e35d19c02\ndf475f6fcc9248b38cd53c33b07c23a9\n9ad492318ea09e0204bdf5e3d5e541c8\nf79e288726f575e29429338318ad5452\nce31226b6a41b39c35975cc02ab08789\n55cf9f9315687b51deb117801adc0a26\n-----END OpenVPN Static key V1-----\n'),
        ),
    ]
