# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0009_auto_20161010_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpnserver',
            name='static_key',
            field=models.TextField(default='#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----\nf4dd69ee8cb7e0dbc49c7f61e811c798\nb6801e3bb622dfb432e1f72340c0a6c7\ncd7f4272865690a158e9b2d3ca3d12f2\n210f975efd7333cd4ec2f726db935c69\n608b8d81abc16ae6b2fcbf472714f52a\ndf8ec24f2ec30d7d076b32985dae03bd\n0079735f6004e32c3980be86db64cf7e\n5aa2b2ec0ac708bba606aab490d962c6\n020accf8b6e7ba7509ce7f73e936c38d\n005f8f61f74d399c51e2962401516ac9\n740d3bbd76bebe4bd0c719af99257322\n7677334492f80f1ea1355f5911da7698\nfe9f5bc921c1bf69a4d4823b153ecbb1\n716a1fb7246c111e57621d8794d3343f\n05cfa1acda4be6ba4ad0f791f2c02fc9\n95e55b3e006366ddd6e2091c12bf5c9b\n-----END OpenVPN Static key V1-----\n'),
        ),
    ]
