# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0010_auto_20161010_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpnserver',
            name='static_key',
            field=models.TextField(default='#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----\nc5fea91efbaf613b9af1e1edbcc68c6f\n7d4c023d4d6fb25254509c02f1f73795\nfb817eb2228fc7d3eb49572c5efbfcf6\nf7a32aa508696ad80c06c7b06c4d5d92\nc789794be6c843360d83760cb6ce564b\n6c6fed429ce3a00b2195e0c80fee475d\n7b122b40cbf6297123e1c6a794785be8\n81d02dbcbced416cd1cc87bc8fab0f7c\n44c4a511a570914151876ff47e2aec7a\n1bf02b5c822809f09a6a8d535df521cf\n711bfd88c35c68a91d5f028fd0d5b0fe\n294135b522c2a446d95a46e7317ae662\n9d250c738e7e25f6e36776ba79e0fd90\n8fba866cffb5558548d10c30855e167d\n1b0b6069b596f5b15ca85457a2e7e9a1\na9e641f579ddd69adec5ef65e711a0b1\n-----END OpenVPN Static key V1-----\n'),
        ),
    ]
