# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0011_auto_20161010_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpnserver',
            name='static_key',
            field=models.TextField(default='#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----\n572852dcd95e0edad72284dd7efdcc53\nbb441aa0d18d5474ef07e015eface4fe\n8b692524740c4390cba39e11956dc3fe\n81a83b3ecec75880c44bf59609646f49\nba0f9765a82e0988b97e20ac952b2b20\n4391e58e3fb2bafb20f07a0295a24377\n2992001d1a6a09fdb5e115d625b6d040\nd9285280086d0e75fb8f204bc75e7402\n0e4124f234f29ec18a5b8008d4f62b88\nc3c6af06e8a6999093838e69bbb9bf6e\n1e37573f6682c1acc2f92426e3825cef\n49e5adfa8f6bcc856d7f8efb1318ede5\nb806c00de26e1601c6c54ed4c6dba307\ne8a92d376722134412f83b0ef2c46505\n232f3f386aba489f7afcb565a39bc248\n423a4a14fcee22ba89741c918748bc90\n-----END OpenVPN Static key V1-----\n'),
        ),
    ]
