# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openvpn', '0012_auto_20161010_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='openvpnserver',
            name='static_key',
            field=models.TextField(default='#\n# 2048 bit OpenVPN static key\n#\n-----BEGIN OpenVPN Static key V1-----\n16c2a13394bcdb02c8937a8888b511e8\n1fab41f1c66e38f1708984c4024503f4\n320121f9467480f2c79cd9a92cbe9131\nad3ad714d05677e83dd9b45dea31ecc8\n155598a4f075404e02f43f107cede815\n416225dcd3ed37422f32b72c254fb6c2\n3cbe4fdd49795e29925eb7bf32be265f\n549e4e60b541c1d77d51a639393ce6e8\ndcf698d6ab5770210e2be61faf6249a8\nf0eabd5e400fb9366da212e440f1c2b1\n7fb6da6334e0586023ebce5a9475af73\nd06c056217cd50625773154072232e05\nf1f229fb361abd53c29e073f4c442b27\n5dd2d0e51cf72ae92cdf29fa84a67d4f\n01759e8411edb9f662b5a206af99d508\n78e35275f9eb3d93bb46ddedaa305c57\n-----END OpenVPN Static key V1-----\n'),
        ),
    ]
