# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-12 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('dev_name', models.CharField(max_length=10, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('netmask', models.GenericIPAddressField(blank=True, null=True)),
                ('dhcp', models.BooleanField(default=True)),
                ('is_wlan_nic', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Wlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ssid', models.CharField(max_length=255)),
                ('wpa_key', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='wlan',
            unique_together=set([('ssid', 'wpa_key')]),
        ),
    ]
