# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-13 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_auto_20161012_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='gateway',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interface',
            name='dev_name',
            field=models.CharField(choices=[('enp0s25', 'enp0s25'), ('virbr0-nic', 'virbr0-nic')], max_length=10, unique=True),
        ),
    ]
